baseURL = 'https://simonqq21.github.io'
languageCode = 'en-us'
title = 'Simon Que' 
theme='ananke' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "academics"
    name = "Academics"
    url = "/academics/"
    weight = 2

  [[menu.main]]
    identifier = "work-experience"
    name = "Work Experience"
    url = "/work-experience/"
    weight = 3

  [[menu.main]]
    identifier = "personal-projects"
    name = "Personal Projects"
    url = "/personal-projects/"
    weight = 4

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6