baseURL = 'https://simonqq21.github.io'
languageCode = 'en-us'
title = 'Simon Que' 
theme='fixit' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menus.main]]
    identifier = "academics"
    name = "Academics"
    url = "/academics/"
    weight = 2

  [[menus.main]]
    identifier = "work-experience"
    name = "Work Experience"
    url = "/work-experience/"
    weight = 3

  [[menus.main]]
    identifier = "personal-projects"
    name = "Personal Projects"
    url = "/personal-projects/"
    weight = 4

  [[menus.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 5

  [[menus.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6

[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"

[params]
  [params.list]
    dateFormat = "2006"